from enum import StrEnum


class EntryType(StrEnum):
    FILE = "file"
    DIRECTORY = "directory"
    SYMLINK = "symlink"
    OTHER = "other"


class Classification(StrEnum):
    KEEP = "KEEP"
    KEEP_CANONICAL = "KEEP_CANONICAL"
    REVIEW_SAFE = "REVIEW_SAFE"
    REVIEW_PROBABLE = "REVIEW_PROBABLE"
    REVIEW_VERSION_FAMILY = "REVIEW_VERSION_FAMILY"
    REVIEW_BACKUP = "REVIEW_BACKUP"
    REVIEW_LARGE = "REVIEW_LARGE"
    PROTECTED = "PROTECTED"
    UNKNOWN = "UNKNOWN"
    ERROR = "ERROR"


class JobStatus(StrEnum):
    RUNNING = "RUNNING"
    COMPLETE = "COMPLETE"
    FAILED = "FAILED"
    INTERRUPTED = "INTERRUPTED"


class MoveStatus(StrEnum):
    PLANNED = "PLANNED"
    MOVED = "MOVED"
    FAILED = "FAILED"
    PARTIAL = "PARTIAL"


class EvidenceTier(StrEnum):
    """Ordered evidence strength; policy rules must never collapse these tiers.

    Only TIER_1_EXACT is eligible for the strongest exact-duplicate review classification by
    default. Everything above requires format-specific evidence and manual review.
    """

    TIER_1_EXACT = "TIER_1_EXACT"
    TIER_2_NORMALIZED_EXACT = "TIER_2_NORMALIZED_EXACT"
    TIER_3_STRONG_EQUIVALENCE = "TIER_3_STRONG_EQUIVALENCE"
    TIER_4_PARTIAL_OVERLAP = "TIER_4_PARTIAL_OVERLAP"
    TIER_5_PROBABILISTIC_SIMILARITY = "TIER_5_PROBABILISTIC_SIMILARITY"
    TIER_6_CONTEXTUAL_INFERENCE = "TIER_6_CONTEXTUAL_INFERENCE"


class ContentRelationshipType(StrEnum):
    """Rich, non-binary duplicate/derivation taxonomy (see docs/duplicate_taxonomy.md)."""

    BYTE_IDENTICAL = "BYTE_IDENTICAL"
    CONTENT_EQUIVALENT = "CONTENT_EQUIVALENT"
    METADATA_VARIANT = "METADATA_VARIANT"
    PIXEL_IDENTICAL = "PIXEL_IDENTICAL"
    ORIENTATION_VARIANT = "ORIENTATION_VARIANT"
    ENCODING_VARIANT = "ENCODING_VARIANT"
    REENCODED_IMAGE = "REENCODED_IMAGE"
    PARTIAL_CONTENT_OVERLAP = "PARTIAL_CONTENT_OVERLAP"
    ARCHIVE_EQUIVALENT = "ARCHIVE_EQUIVALENT"
    ARCHIVE_REPACKAGING_VARIANT = "ARCHIVE_REPACKAGING_VARIANT"
    ARCHIVE_OF_DIRECTORY = "ARCHIVE_OF_DIRECTORY"
    OFFICE_PACKAGE_EQUIVALENT = "OFFICE_PACKAGE_EQUIVALENT"
    OFFICE_TEXT_EQUIVALENT = "OFFICE_TEXT_EQUIVALENT"
    LIKELY_COPY = "LIKELY_COPY"
    LIKELY_VERSION = "LIKELY_VERSION"
    LIKELY_EXPORT = "LIKELY_EXPORT"
    LIKELY_RENDERING = "LIKELY_RENDERING"
    LIKELY_DERIVED = "LIKELY_DERIVED"
    VISUALLY_SIMILAR = "VISUALLY_SIMILAR"
    SEMANTICALLY_SIMILAR = "SEMANTICALLY_SIMILAR"


class CanonicalRole(StrEnum):
    """Role-based preservation assignments; a group may fill several roles with different files."""

    PRESERVATION_MASTER = "PRESERVATION_MASTER"
    EDITABLE_SOURCE = "EDITABLE_SOURCE"
    FINAL_EXPORT = "FINAL_EXPORT"
    PUBLISHED_COPY = "PUBLISHED_COPY"
    ACCESS_COPY = "ACCESS_COPY"
    BEST_METADATA_COPY = "BEST_METADATA_COPY"
    HIGHEST_FIDELITY_COPY = "HIGHEST_FIDELITY_COPY"
    CANONICAL_LOCATION = "CANONICAL_LOCATION"


class AnalysisArtifactStatus(StrEnum):
    OK = "OK"
    ERROR = "ERROR"
    UNSUPPORTED = "UNSUPPORTED"
    SKIPPED = "SKIPPED"


class ClusterType(StrEnum):
    PHOTO_EVENT = "PHOTO_EVENT"
    WORK_SESSION = "WORK_SESSION"
    ACQUISITION_BATCH = "ACQUISITION_BATCH"
    DOCUMENT_FAMILY = "DOCUMENT_FAMILY"
    BACKUP_FAMILY = "BACKUP_FAMILY"
    PROJECT_COLLECTION = "PROJECT_COLLECTION"
    RECORD_SERIES = "RECORD_SERIES"


class LifecycleState(StrEnum):
    """Non-binary lifecycle states; manual deletion always stays outside Housekeeper."""

    ACTIVE = "ACTIVE"
    ARCHIVE = "ARCHIVE"
    COLD_ARCHIVE = "COLD_ARCHIVE"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    PROTECTED = "PROTECTED"
    DEFERRED = "DEFERRED"


class ReviewPriorityCategory(StrEnum):
    QUICK_SAFE_WIN = "QUICK_SAFE_WIN"
    HIGH_VALUE_REVIEW = "HIGH_VALUE_REVIEW"
    CONTEXT_REQUIRED = "CONTEXT_REQUIRED"
    PRESERVATION_FIRST = "PRESERVATION_FIRST"
    LOW_PRIORITY = "LOW_PRIORITY"


class CollectionValue(StrEnum):
    HIGH_MARGINAL_VALUE = "HIGH_MARGINAL_VALUE"
    MODERATE_MARGINAL_VALUE = "MODERATE_MARGINAL_VALUE"
    LOW_BYTE_VALUE_HIGH_CONTEXT_VALUE = "LOW_BYTE_VALUE_HIGH_CONTEXT_VALUE"
    MOSTLY_REDUNDANT_WITH_UNIQUE_ITEMS = "MOSTLY_REDUNDANT_WITH_UNIQUE_ITEMS"
    FULLY_CONTENT_REDUNDANT_CONTEXT_REMAINS = "FULLY_CONTENT_REDUNDANT_CONTEXT_REMAINS"
    UNRESOLVED = "UNRESOLVED"


#: What a digest recorded before its algorithm was written down was computed with. Manifests and
#: transaction records that predate ``expected_hash_algorithm`` were always SHA-256.
LEGACY_HASH_ALGORITHM = "sha256"
SCHEMA_VERSION = 9
PROTECTED_SUFFIXES = {
    ".pem",
    ".key",
    ".kdbx",
    ".wallet",
    ".db",
    ".sqlite",
    ".sqlite3",
    ".gpg",
}
