"""The one-command quickstart pipeline.

Covers the summary shape, correctness of the current-snapshot totals, idempotent re-runs (the
easy-button is meant to be re-run), and the read-only invariant: quickstart must never modify,
move, or delete anything under the source tree, and must never create a review/move folder.
"""

import pytest

from housekeeper.config import load_config
from housekeeper.database import Database
from housekeeper.quickstart import next_steps, run_quickstart


def _drive(tmp_path):
    root = tmp_path / "drive"
    original = root / "Original"
    backup = root / "Backup"
    original.mkdir(parents=True)
    backup.mkdir(parents=True)
    for name in ("one.txt", "two.txt", "three.txt"):
        (original / name).write_text(f"shared content {name}", encoding="utf-8")
        (backup / name).write_text(f"shared content {name}", encoding="utf-8")  # exact duplicates
    (original / "main.py").write_text("print('unique')", encoding="utf-8")
    return root


def _fresh(tmp_path, name="ws"):
    config = load_config(workspace_override=tmp_path / name)
    database = Database(config.database_path)
    database.initialize()
    return database, config


def _snapshot(root):
    # (relative path, size, mtime) for every file under the source, to prove nothing changed.
    return {
        str(p.relative_to(root)): (p.stat().st_size, p.stat().st_mtime)
        for p in sorted(root.rglob("*"))
        if p.is_file()
    }


def test_quickstart_runs_full_pipeline(tmp_path):
    root = _drive(tmp_path)
    database, config = _fresh(tmp_path)
    summary = run_quickstart(database, config, root)
    totals = summary["totals"]
    assert totals["files"] == 7
    assert totals["directories"] == 2
    assert totals["content_objects"] == 4  # 3 shared txt + 1 unique py
    assert totals["exact_duplicate_groups"] == 3  # the three txt pairs
    assert totals["duplicate_files"] == 3  # one redundant copy per pair
    assert summary["reports"], "reports should be generated by default"
    # Every step ran and recorded an outcome.
    step_names = {step["step"] for step in summary["steps"]}
    for expected in ("scan", "exact-duplicates", "classify", "reports", "contact-sheets"):
        assert expected in step_names


def test_quickstart_is_idempotent(tmp_path):
    root = _drive(tmp_path)
    database, config = _fresh(tmp_path)
    first = run_quickstart(database, config, root, generate_reports=False)["totals"]
    second = run_quickstart(database, config, root, generate_reports=False)["totals"]
    third = run_quickstart(database, config, root, generate_reports=False)["totals"]
    # Re-running the easy-button on the same drive reports the same current-snapshot picture.
    assert first == second == third


def test_quickstart_never_modifies_the_source(tmp_path):
    root = _drive(tmp_path)
    before = _snapshot(root)
    database, config = _fresh(tmp_path)
    run_quickstart(database, config, root)
    after = _snapshot(root)
    assert before == after, "quickstart must not add, remove, or modify any source file"


def test_quickstart_creates_no_move_or_review_folder(tmp_path):
    root = _drive(tmp_path)
    database, config = _fresh(tmp_path)
    run_quickstart(database, config, root)
    # Movement is a separate explicit flow; quickstart must never stage or move files.
    for suspicious in ("review", "REVIEW", "to-review", "quarantine"):
        assert not (root / suspicious).exists()


def test_quickstart_no_reports_flag(tmp_path):
    root = _drive(tmp_path)
    database, config = _fresh(tmp_path)
    summary = run_quickstart(database, config, root, generate_reports=False)
    assert "reports" not in summary
    assert not any(step["step"] == "reports" for step in summary["steps"])


def test_quickstart_records_durable_jobs(tmp_path):
    root = _drive(tmp_path)
    database, config = _fresh(tmp_path)
    run_quickstart(database, config, root, generate_reports=False)
    jobs = database.fetch_all("SELECT job_type,status FROM jobs")
    assert jobs, "quickstart steps run inside tracked jobs"
    # Every step completed (COMPLETED, or COMPLETED_WITH_ERRORS if an optional parser was missing).
    assert all(job["status"] in {"COMPLETED", "COMPLETED_WITH_ERRORS"} for job in jobs)
    assert any(job["job_type"] == "SCAN" for job in jobs)


def test_next_steps_are_advisory_and_mention_safety(tmp_path):
    _, config = _fresh(tmp_path)
    steps = next_steps(config)
    assert any("dashboard" in step for step in steps)
    joined = " ".join(steps).lower()
    assert "read-only" in joined and "deleted" in joined  # reiterates the never-delete invariant


def test_rerun_never_flags_unique_files_as_reviewable(tmp_path):
    # Regression: the tool keeps scan history, so an unscoped exact-duplicate pass would group a
    # unique file with its own prior-scan snapshot and classify the current copy REVIEW_SAFE — which
    # would make irreplaceable single-copy files eligible for the move-to-review flow on a routine
    # re-run. Quickstart scopes analysis to the current scan run, so unique files stay KEEP forever.
    root = tmp_path / "unique"
    root.mkdir()
    (root / "resume.txt").write_text("the only copy of my resume", encoding="utf-8")
    (root / "taxes.txt").write_text("the only copy of my taxes", encoding="utf-8")
    (root / "notes.md").write_text("# unique notes", encoding="utf-8")
    database, config = _fresh(tmp_path)
    for _ in range(3):
        run_quickstart(database, config, root, generate_reports=False)
        current = database.fetch_all(
            "SELECT c.classification FROM classifications c JOIN filesystem_entries e ON e.id=c.entry_id "
            "WHERE e.scan_run_id=(SELECT MAX(id) FROM scan_runs) AND e.entry_type='file'"
        )
        assert current, "expected the current snapshot to be classified"
        reviewable = [
            row["classification"]
            for row in current
            if str(row["classification"]).startswith("REVIEW")
        ]
        assert reviewable == [], f"unique files must never become reviewable, got {reviewable}"


def test_genuine_duplicates_are_still_detected(tmp_path):
    # The scoping fix must not suppress real intra-snapshot duplicates.
    root = _drive(tmp_path)  # Original/* and Backup/* are byte-identical
    database, config = _fresh(tmp_path)
    totals = run_quickstart(database, config, root, generate_reports=False)["totals"]
    assert totals["exact_duplicate_groups"] == 3
    assert totals["duplicate_files"] == 3


def test_quickstart_rejects_nonexistent_source(tmp_path):
    database, config = _fresh(tmp_path)
    with pytest.raises(FileNotFoundError):
        run_quickstart(database, config, tmp_path / "does-not-exist")


def test_quickstart_rejects_file_source(tmp_path):
    afile = tmp_path / "a.txt"
    afile.write_text("x", encoding="utf-8")
    database, config = _fresh(tmp_path)
    with pytest.raises(NotADirectoryError):
        run_quickstart(database, config, afile)


def test_quickstart_tracks_canonical_roles_stage(tmp_path):
    # Every stage, including canonical-role assignment, runs inside a recorded durable job.
    root = _drive(tmp_path)
    database, config = _fresh(tmp_path)
    summary = run_quickstart(database, config, root, generate_reports=False)
    assert any(step["step"] == "canonical-roles" for step in summary["steps"])


def test_quickstart_bad_source_exits_nonzero_cli(tmp_path):
    from housekeeper.cli import main

    code = main(["--workspace", str(tmp_path / "ws"), "quickstart", str(tmp_path / "missing")])
    assert code == 1  # clean error via the top-level guard, not a traceback


def test_quickstart_cli_smoke(tmp_path, capsys):
    from housekeeper.cli import main

    root = _drive(tmp_path)
    code = main(["--workspace", str(tmp_path / "cli_ws"), "quickstart", str(root), "--no-reports"])
    assert code == 0
    out = capsys.readouterr().out
    assert "Quickstart complete" in out
    assert "nothing was moved or deleted" in out
