from typing import Any, Protocol


class AccelerationBackend(Protocol):
    def capabilities(self) -> dict[str, Any]: ...
    def full_hash(self, path: str, algorithm: str, block_size: int) -> dict[str, Any]: ...
    def quick_hash(self, path: str, algorithm: str, chunk_size: int, middle_samples: int) -> dict[str, Any]: ...
    def identity_hash(self, path: str, algorithm: str, block_size: int, quick_chunk_size: int, middle_samples: int) -> dict[str, Any]: ...
    def scan(self, path: str) -> dict[str, Any]: ...
    def aggregate_directories(self, entries: list[dict[str, Any]]) -> dict[str, Any]: ...
    def verify_manifest(self, entries: list[dict[str, Any]]) -> dict[str, Any]: ...
    def copy_and_verify(self, source: str, destination: str, expected_hash: str, algorithm: str) -> dict[str, Any]: ...
